language: perl
sudo: false

matrix:
  include:
  - perl: "5.30"
  - perl: "5.26"
  - perl: "5.22"

env:
  global:
   - "CONVOS_DEBUG=1"
   - "HARNESS_OPTIONS=v"
   - "TEST_BOT=1"
   - "TEST_POD=1"

install:
  - cpanm -n EV~"!= 4.28"
  - cpanm -n DBD::SQLite Hailo Math::Calc::Parser
  - cpanm -n https://github.com/jhthorsen/linkembedder/archive/master.tar.gz
  - cpanm -n Test::Pod Test::Pod::Coverage
  - cpanm -n --installdeps .

notifications:
  email:
    recipients:
      - jhthorsen@cpan.org
    on_failure: change
    on_success: change
